Save and update task time_end to db
bionfinc/pomodoro pull request #64
Opened 2020-07-30 05:28 UTC by dmichaelhanson

Created a JS function called updateTimeEnd() that does an ajax call to new view function called update-task_time_end that will create/update the time_end for a task in the database. This is called from the pauseTimer() function for logged in users and only runs if its a pomodoro.  This should make it update the end time any time the clock stops for whatever reason including being paused by the user, reset by the user, switching to a rest, or the clock reaching 0. 

If the clock is paused then resumed, the time_end will be updated again with the end time when the clock reaches 0 (or it is paused/stopped again)

2020-07-30 13:47 UTC, ja-osu requested changes
In function updateTimeEnd()

Can you change if(currentTimer == "Pomodoro")
to
if(currentTimer == "Pomodoro" && timerState != 'STOPPED' && timerState != '')

This will prevent a call to the database when the user first logs in (if they would happen to hit the pause button), and after a task has finished (if the user would hit pause after the timer has stopped but before a new Pomodoro task has started).

Otherwise, everything works perfect.

2020-07-30 22:36 UTC, adorgan approved these changes
Tested and works well, and I agree with Janet's comments.

2020-07-31 04:36 UTC, dmichaelhanson commented
made requested change for if(currentTimer == "Pomodoro" && timerState != 'STOPPED' && timerState != '')

2020-07-31 12:27 UTC, ja-osu approved these changes

2020-07-31 12:28 UTC, merged